### ISSUE TITLE
Error in the download_tweets.py file

### ISSUE THREAD

**Issue by sarathakare** [YLab-Open/METS-CoV#2]
The output_dir, hydrated_dir paths are not properly defined

**Comment by sarathakare** [comment]
the variable hydrated_dir is not defined anywhere in the code, but it is used when creating directories.  it appears that the intention is to use output_dir.

**Comment by jiesutd** [comment]
The Twitter API may changed. You can download the date directly from a user posted: https://github.com/YLab-Open/METS-CoV/issues/1
